const restaurantsData = [
    {
        avgRating: 3.0,
        name: "Pratap Palace",
        cuisines: ["Italian", "Chinese, Fast Food"],
        locality: "Raebareli",
        costForTwo: "$15 avg",
        time: "30-40 min",
        img: "y4cn67prvzexwqkoqasp",
    },
    {
        avgRating: 4.2,
        name: "Spicy Treat",
        cuisines: ["North Indian", "Chinese"],
        locality: "Lucknow",
        costForTwo: "$20 avg",
        time: "25-35 min",
        img: "y4cn67prvzexwqkoqasp",
    },
    {
        avgRating: 3.8,
        name: "Foodie's Hub",
        cuisines: ["Fast Food", "Burgers", "Wraps"],
        locality: "Kanpur",
        costForTwo: "$10 avg",
        time: "20-30 min",
        img: "y4cn67prvzexwqkoqasp",
    },
    {
        avgRating: 4.5,
        name: "Royal Biryani",
        cuisines: ["Biryani", "Mughlai"],
        locality: "Hyderabad",
        costForTwo: "$18 avg",
        time: "30-40 min",
        img: "y4cn67prvzexwqkoqasp",
    },
    {
        avgRating: 4.0,
        name: "Chatori Gali",
        cuisines: ["Chaat", "Snacks", "Street Food"],
        locality: "Delhi",
        costForTwo: "$8 avg",
        time: "15-25 min",
        img: "y4cn67prvzexwqkoqasp",
    },
    {
        avgRating: 3.6,
        name: "Desi Tadka",
        cuisines: ["North Indian", "Thali"],
        locality: "Allahabad",
        costForTwo: "$12 avg",
        time: "25-35 min",
        img: "y4cn67prvzexwqkoqasp",
    },
    {
        avgRating: 4.1,
        name: "South Spice",
        cuisines: ["South Indian"],
        locality: "Chennai",
        costForTwo: "$14 avg",
        time: "20-30 min",
        img: "y4cn67prvzexwqkoqasp",
    },
    {
        avgRating: 4.3,
        name: "Flavours of Punjab",
        cuisines: ["Punjabi", "Tandoori"],
        locality: "Amritsar",
        costForTwo: "$22 avg",
        time: "30-45 min",
        img: "y4cn67prvzexwqkoqasp",
    },
    {
        avgRating: 3.9,
        name: "Coastal Cravings",
        cuisines: ["Seafood", "Goan"],
        locality: "Goa",
        costForTwo: "$25 avg",
        time: "35-45 min",
        img: "y4cn67prvzexwqkoqasp",
    },
    {
        avgRating: 4.6,
        name: "Bakers Den",
        cuisines: ["Bakery", "Desserts"],
        locality: "Mumbai",
        costForTwo: "$9 avg",
        time: "15-20 min",
        img: "y4cn67prvzexwqkoqasp",
    },
    {
        avgRating: 3.5,
        name: "Chinese Bowl",
        cuisines: ["Chinese", "Asian"],
        locality: "Kolkata",
        costForTwo: "$16 avg",
        time: "25-35 min",
        img: "y4cn67prvzexwqkoqasp",
    },
    {
        avgRating: 4.4,
        name: "Tandoor Flames",
        cuisines: ["Tandoori", "Grill"],
        locality: "Jaipur",
        costForTwo: "$19 avg",
        time: "30-40 min",
        img: "y4cn67prvzexwqkoqasp",
    },
    {
        avgRating: 3.7,
        name: "Veggie Delight",
        cuisines: ["Vegetarian", "Salads"],
        locality: "Pune",
        costForTwo: "$13 avg",
        time: "20-30 min",
        img: "y4cn67prvzexwqkoqasp",
    },
    {
        avgRating: 4.0,
        name: "Kathi Junction",
        cuisines: ["Rolls", "Fast Food"],
        locality: "Varanasi",
        costForTwo: "$11 avg",
        time: "15-25 min",
        img: "y4cn67prvzexwqkoqasp",
    },
    {
        avgRating: 4.1,
        name: "Dilli Zaika",
        cuisines: ["Mughlai", "North Indian"],
        locality: "Delhi",
        costForTwo: "$17 avg",
        time: "30-40 min",
        img: "y4cn67prvzexwqkoqasp",
    },
    {
        avgRating: 4.3,
        name: "Midnight Meals",
        cuisines: ["Snacks", "Wraps", "Drinks"],
        locality: "Noida",
        costForTwo: "$15 avg",
        time: "20-30 min",
        img: "y4cn67prvzexwqkoqasp",
    },
];

export default restaurantsData;
